spring:
  datasource:
    url: ${DATABASE_JDBC_URL:jdbc:postgresql://localhost:5432/nodevoltex_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8082}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

servlet:
  multipart:
    max-file-size: 5MB
    max-request-size: 5MB

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours in milliseconds